apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  namespace: diploe2-hejr
spec:
  steps:
  - name: echo
    image: busybox
    script: |
      #!/bin/sh
      echo "Hello, World from Tekton! Modulo5-Ejercicio6-HEJR"
