apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
 generateName: pipelinerun-ci-
 namespace: diploe2-hejr
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: pipeline-ci
  params:
    - name: repo-url
      value: https://github.com/hugoemiliojara7/DCN_ProyectoFinal_HEJR_tripAPI
    - name: maven-image
      value: gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b
    - name: docker-image-version
      value: docker.io/hugoejara7/tripapi:v4
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: maven-settings
      configmap:
        name: maven-settings
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - name: dockerconfig
      secret:
        secretName: dockerconfig-secret
