apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-run-
  namespace: diploe2-hejr
spec:
  podTemplate:
    securityContext: 
      fsGroup: 65532
  taskRef:
    kind: Task
    name: buildah
  params:
    - name: IMAGE
      value: 'docker.io/hugoejara7/tripapi:v3'
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - name: dockerconfig
      secret:
        secretName: dockerconfig-secret
